
management:
  health:
    circuitbreakers:
      enabled: true
  endpoints:
    web:
      exposure:
        include: health
  endpoint:
    health:
      show-details: always

resilience4j:
  circuitbreaker:
    instances:
      DEPARTMENT-SERVICE:
        registerHealthIndicator: true
        eventConsumerBufferSize: 10
        failureRateThreshold: 50
        minimumNumberOfCalls: 5
        automaticTransitionFromOpenToHalfOpenEnabled: true
        waitDurationInOpenState: 5s
        permittedNumberOfCallsInHalfOpenState: 3
        slidingWindowSize: 10
        slidingWindowType: COUNT_BASED

resilience4j.retry:
  instances:
    serviceA:
      maxAttempts: 10
      waitDuration: 10s
server:
  port: 8181
spring:
  application:
    name: API_GATEWAY
  cloud:
    gateway:
      routes:
        - id: DEPARTMENT-SERVICE
          uri: lb://DEPARTMENT-SERVICE
          predicates :
            - Path=/department/**
#          filters:
#            - name: CircuitBreaker
#              args:
#                name: DEPARTMENT-SERVICE
#                fallbackUri:

        - id: USER-SERVICE
          uri: lb://USER-SERVICE
          predicates:
            - Path=Path=/user/**





